# Learn more about configuring your Customer account UI extension:
# https://shopify.dev/api/customer-account-ui-extensions/unstable/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2025-07"

[[extensions]]
name = "Trust badge"
handle = "trust-badge"
type = "ui_extension"


# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/OrderStatusBlock.jsx"
target = "customer-account.order-status.block.render"

[[extensions.targeting]]
module = "./src/OrderIndexBlock.jsx"
target = "customer-account.order-index.block.render"

[[extensions.targeting]]
module = "./src/ProfileBlock.jsx"
target = "customer-account.profile.block.render"


[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/configuration#network-access
# network_access = true


[extensions.settings]
[[extensions.settings.fields]]
key = "image_one"
type = "single_line_text_field"
name = "Image 1 URL"
description = "Provide the URL for Image 1"

[[extensions.settings.fields]]
key = "title_one"
type = "single_line_text_field"
name = "Title 1"
description = "Enter Title 1 Text"

[[extensions.settings.fields]]
key = "image_two"
type = "single_line_text_field"
name = "Image 2 URL"
description = "Provide the URL for Image 2"

[[extensions.settings.fields]]
key = "title_two"
type = "single_line_text_field"
name = "Title 2"
description = "Enter Title 2 Text"

[[extensions.settings.fields]]
key = "image_three"
type = "single_line_text_field"
name = "Image 3 URL"
description = "Provide the URL for Image 3"

[[extensions.settings.fields]]
key = "title_three"
type = "single_line_text_field"
name = "Title 3"
description = "Enter Title 3 Text"

[[extensions.settings.fields]]
key = "image_width"
type = "number_integer"
name = "Image Width"
description = "Enter the width of the image in pixels, for example: 60 | 70 | 80 | 100"

[[extensions.settings.fields]]
key = "title_size"
type = "single_line_text_field"
name = "Title Font Size"
description = "Select the font size for the title"
[[extensions.settings.fields.validations]]
name = "choices"
value = "[\"extraSmall\", \"small\", \"base\", \"large\", \"extraLarge\", \"medium\"]"

[[extensions.settings.fields]]
key = "title_color"
type = "single_line_text_field"
name = "Title Font Color"
description = "Select the font color for the title"
[[extensions.settings.fields.validations]]
name = "choices"
value = "[\"base\", \"accent\", \"decorative\", \"interactive\", \"subdued\", \"info\", \"success\", \"warning\", \"critical\", \"monochrome\"]"

[[extensions.settings.fields]]
key = "title_emphasis"
type = "single_line_text_field"
name = "Title Font Weight"
description = "Select the font weight for title"
[[extensions.settings.fields.validations]]
name = "choices"
value = "[\"normal\", \"italic\", \"bold\"]"